server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://project-one-ngo-mysqldb.cyklodfpa0tq.us-east-1.rds.amazonaws.com:3306/microservices
    username: admin
    password: Simple-123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
